### PR TITLE
Job Application

### PR DESCRIPTION
**Pull request by khandragon**
Create front end to create applications to post

### CODE REVIEW

**Review by Bogdanpoda — CHANGES_REQUESTED** [review]
error  cannot get application because the school end is not a date there is an Type error
image

**Review by khandragon — COMMENTED** [review]
Changed how the backend handles the date back to how it was originally.

**Review by Bogdanpoda — APPROVED** [review]
ok

**Comment by MatthewBeaulieu0** [comment]
Thank you bogdan for approving 👍

**Pull request merged**
